import { IDisplayOptions } from 'n8n-workflow';
import { IAmojoProperties } from '../../interfaces';

const displayOptions: IDisplayOptions | undefined = {
	show: {
		resource: ['amojo'],
		operation: ['sendMessage'],
	},
};

export const description: IAmojoProperties = [
	{
		displayName: 'Scope ID',
		name: 'scopeId',
		type: 'string',
		default: '',
		required: true,
		displayOptions,
		description: 'First ID from /v1/chats/{scopeId}/{chatId}/messages',
	},
	{
		displayName: 'Chat ID',
		name: 'chatId',
		type: 'string',
		default: '',
		required: true,
		displayOptions,
		description: 'Second ID from /v1/chats/{scopeId}/{chatId}/messages',
	},
	{
		displayName: 'With Video',
		name: 'with_video',
		type: 'boolean',
		default: true,
		displayOptions,
	},
	{
		displayName: 'Stand',
		name: 'stand',
		type: 'string',
		default: 'v16',
		displayOptions,
	},
	{
		displayName: 'Use AJAX Header',
		name: 'useAjaxHeader',
		type: 'boolean',
		default: true,
		displayOptions,
		description: 'Whether to add X-Requested-With: XMLHttpRequest header',
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		default: '',
		required: true,
		displayOptions,
		description: 'Message text',
	},
	{
		displayName: 'CRM Entity ID',
		name: 'crmEntityId',
		type: 'number',
		typeOptions: {
			minValue: 1,
			numberStepSize: 1,
		},
		default: 0,
		required: true,
		displayOptions,
		description: 'CRM entity ID (for example, lead ID)',
	},
	{
		displayName: 'CRM Entity Type',
		name: 'crmEntityType',
		type: 'number',
		typeOptions: {
			minValue: 1,
			numberStepSize: 1,
		},
		default: 2,
		required: true,
		displayOptions,
		description: 'CRM entity type code. Common value for lead is 2.',
	},
	{
		displayName: 'Recipient ID',
		name: 'recipientId',
		type: 'string',
		default: '',
		required: true,
		displayOptions,
		description: 'Recipient identifier from chat context',
	},
	{
		displayName: 'CRM Dialog ID',
		name: 'crmDialogId',
		type: 'number',
		typeOptions: {
			minValue: 1,
			numberStepSize: 1,
		},
		default: 0,
		required: true,
		displayOptions,
		description: 'Dialog ID in CRM',
	},
	{
		displayName: 'CRM Contact ID',
		name: 'crmContactId',
		type: 'number',
		typeOptions: {
			minValue: 1,
			numberStepSize: 1,
		},
		default: 0,
		required: true,
		displayOptions,
		description: 'Contact ID in CRM',
	},
	{
		displayName: 'CRM Account ID',
		name: 'crmAccountId',
		type: 'number',
		typeOptions: {
			minValue: 1,
			numberStepSize: 1,
		},
		default: 0,
		required: true,
		displayOptions,
		description: 'Account ID in CRM',
	},
	{
		displayName: 'Priority',
		name: 'priority',
		type: 'options',
		options: [
			{
				name: 'Low',
				value: 'low',
			},
			{
				name: 'Normal',
				value: 'normal',
			},
			{
				name: 'High',
				value: 'high',
			},
		],
		default: 'low',
		displayOptions,
	},
	{
		displayName: 'Silent',
		name: 'silent',
		type: 'boolean',
		default: false,
		displayOptions,
	},
	{
		displayName: 'Skip Link Shortener',
		name: 'skipLinkShortener',
		type: 'boolean',
		default: true,
		displayOptions,
	},
	{
		displayName: 'Set Personalization',
		name: 'setPersonalization',
		type: 'boolean',
		default: false,
		displayOptions,
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions,
		options: [
			{
				displayName: 'Group ID',
				name: 'groupId',
				type: 'string',
				default: '',
				description: 'Optional group ID. Keep empty to send null.',
			},
			{
				displayName: 'Persona Name',
				name: 'personaName',
				type: 'string',
				default: '',
				description: 'Optional sender name',
			},
			{
				displayName: 'Persona Avatar',
				name: 'personaAvatar',
				type: 'string',
				default: '',
				description: 'Optional sender avatar URL',
			},
		],
	},
];
